export default [
  {id: 0, genre: 'Acoustic'},
  {id: 1, genre: 'African'},
  {id: 2, genre: 'Alternative Rock'},
  {id: 3, genre: 'Ambient'},
  {id: 4, genre: 'Asian Pop'},
  {id: 5, genre: 'Bass'},
  {id: 6, genre: 'Bass House'},
  {id: 7, genre: 'Big Room'},
  {id: 8, genre: 'Bollywood'},
  {id: 9, genre: 'Breakbeat'},
  {id: 10, genre: 'Chill Out'},
  {id: 11, genre: 'Classical'},
  {id: 12, genre: 'Complextro'},
  {id: 13, genre: 'Country'},
  {id: 14, genre: 'Dance'},
  {id: 15, genre: 'Deep House'},
  {id: 16, genre: 'Disco'},
  {id: 17, genre: 'Downtempo'},
  {id: 18, genre: 'Drum & Bass'},
  {id: 19, genre: 'Dub'},
  {id: 20, genre: 'Dub Techno'},
  {id: 21, genre: 'EDM'},
  {id: 22, genre: 'Electro'},
  {id: 23, genre: 'Electronic'},
  {id: 24, genre: 'Experimental'},
  {id: 25, genre: 'Folk'},
  {id: 26, genre: 'Footwork'},
  {id: 27, genre: 'Funk'},
  {id: 28, genre: 'Future Bass'},
  {id: 29, genre: 'Future House'},
  {id: 30, genre: 'G House'},
  {id: 31, genre: 'Glitch'},
  {id: 32, genre: 'Glitch Hop'},
  {id: 33, genre: 'Grime'},
  {id: 34, genre: 'Hardcore'},
  {id: 35, genre: 'Hardstyle'},
  {id: 36, genre: 'Acoustic'},
  {id: 37, genre: 'Acoustic'},
  {id: 38, genre: 'Acoustic'},
  {id: 39, genre: 'Acoustic'}
  // 'Hip Hop',
  // 'House',
  // 'IDM',
  // 'Indie',
  // 'Jazz',
  // 'Latin',
  // 'Lofi Hip Hop',
  // 'Lofi House',
  // 'Melbourne',
  // 'Metal',
  // 'Minimal',
  // 'Moombahton',
  // 'Neo Soul',
  // 'Neuro',
  // 'Nu Disco',
  // 'Piano',
  // 'Pop',
  // 'Progressive House',
  // 'Psytrance',
  // 'R&B',
  // 'Rap',
  // 'Reggae',
  // 'Reggaeton',
  // 'Riddim',
  // 'Rock',
  // 'Soul',
  // 'Sound FX',
  // 'Soundtrack',
  // 'Synthpop',
  // 'Tech House',
  // 'Techno',
  // 'Trance',
  // 'Trap',
  // 'Tribal House',
  // 'Trip Hop',
  // 'Tropical House',
  // 'UK Garage',
  // 'World'
];
